### ISSUE TITLE
change the require of /node_modules/nordigen-node/lib/index.js to a dynamic import() which is available in all CommonJS modules

### ISSUE THREAD

**Issue by AnthonyNahas** [nordigen/nordigen-node#31]
**Describe the bug**

I am trying to integration nordigen-node v1.1.1 into my firebase cloud function

my package is using 

```json
  "compilerOptions": {
    "module": "commonjs",
```

**To Reproduce**
1. Specify API endpoint
2. Specify response & error message

**Expected behavior**

**Screenshots**
![Bildschirmfoto 2022-10-26 um 21 00 20](https://user-images.githubusercontent.com/20149774/198113450-311a3c95-1ebe-44b7-98b9-938f1535cfdd.png)

**Additional context**

Whenever I try to upload my functions, the deploy will exit with the code shown in the above screeshot

**Comment by AnthonyNahas** [comment]
I think we need something like the following to support `commonJS` module

```
// mod.cjs
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
```

https://github.c
![Bildschirmfoto 2022-10-26 um 21 35 43](https://user-images.githubusercontent.com/20149774/198120076-d8e3cf1f-c6dc-46de-b713-d58062444a17.png)
om/node-fetch/node-fetch#commonjs

**Comment by victory-sokolov** [comment]
@AnthonyNahas  
We migrated from node-fetch to axios, could you please take a look if this fixes your problem.

**Comment by prasadKodeInCloud** [comment]
I noticed the same issue in my NestJs project build. May be this issue is not related to the node-fetch. 
nordigen-node version is **1.2.0**


`/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js:16
        return originalLoader.apply(this, arguments);
                              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/nordigen-node/lib/index.js from /dist/packages/myapp/api/main.js not supported.
Instead change the require of index.js in /dist/packages/myapp/api/main.js to a dynamic import() which is available in all CommonJS modules.
    at Function.Module._load (/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js:16:31)
    at Object.nordigen-node (/dist/packages/myapp/api/main.js:37884:18)
    at __webpack_require__ (/dist/packages/myapp/api/main.js:37985:42)
    at Object../packages/myapp/api/src/app/nordigen/nordigen.service.ts (/dist/packages/myapp/api/main.js:22958:54)
    at __webpack_require__ (/dist/packages/myapp/api/main.js:37985:42)
    at Object../packages/myapp/api/src/app/nordigen/nordigen.controller.ts (/dist/packages/myapp/api/main.js:22851:28)
    at __webpack_require__ (/dist/packages/myapp/api/main.js:37985:42)
    at Object../packages/myapp/api/src/app/nordigen/nordigen.module.ts (/dist/packages/myapp/api/main.js:22932:31)
    at __webpack_require__ (/dist/packages/myapp/api/main.js:37985:42)
    at Object../packages/myapp/api/src/app/app.module.ts (/dist/packages/myapp/api/main.js:22265:27)
    at __webpack_require__ (/dist/packages/myapp/api/main.js:37985:42)
    at /dist/packages/myapp/api/main.js:38007:22
    at /dist/packages/myapp/api/main.js:38034:3
    at Object.<anonymous> (/dist/packages/myapp/api/main.js:38039:12)
    at Function.Module._load (/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js:16:31)
    at Object.<anonymous> (/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js:19:1)`

**Comment by jannikhst** [comment]
Just use my fork or create your own fork and copy my last two commits...
`npm install jannikhst/nordigen-node`

**Comment by zakariamehbi** [comment]
I'm using `import NordigenClient from 'nordigen-node'` and have the same error : 
```
require() of ES Module node_modules/nordigen-node/lib/index.js from '' not supported.
Instead change the require of index.js in '...' to a dynamic import() which is available in all CommonJS modules.
```

**Comment by trasua** [comment]
> 

I have the same issue
Node v16.17.0
nordigen-node v1.1.1 and v1.2.1

**Comment by zakariamehbi** [comment]
Wasted so much time on it. Just wrote my own controller ( https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/#/accounts/accounts_transactions_retrieve )

**Comment by prasadKodeInCloud** [comment]
Typescript support also is not great in this package. I ended up creating a package with zod types directly calling api

**Comment by victory-sokolov** [comment]
@zakariamehbi @blueyellowpink 
Sorry for the delay. We've made a fix, could please try with the latest version 1.2.2
